name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      shell: cmd
      run: |
        cmake -S . -B ./PrjVisualStudio -G "Visual Studio 16 2019" -A x64
        cmake --build ./PrjVisualStudio --config "Release"
